- name: install Tomcat and all tools
  import_tasks: tomcat_install.yml

- name: build the springboot application
  import_tasks: build.yml



# - name: Inject MongoDB URI as env var
#   import_tasks: set_env.yml


