- name: Install Tomcat on public EC2
  hosts: Tomcat
  become: true
  roles:
    - tomcat


  # vars:
  #   mongo_ip: "{{ hostvars[groups['MongoDB'][0]].ansible_default_ipv4.address }}"
  #   mongo_uri: "mongodb://{{ mongo_ip }}:27017/devopsdb"
