- name: Import MongoDB public GPG key
  apt_key:
    url: https://www.mongodb.org/static/pgp/server-6.0.asc
    state: present

- name: Create MongoDB repo list
  copy:
    dest: /etc/apt/sources.list.d/mongodb-org-6.0.list
    content: |
      deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu jammy/mongodb-org/6.0 multiverse

- name: Update APT cache
  apt:
    update_cache: yes

- name: Install MongoDB
  apt:
    name: mongodb-org
    state: present

- name: Start and enable MongoDB
  service:
    name: mongod
    state: started
    enabled: true

- name: Allow connections from any host (0.0.0.0)
  lineinfile:
    path: /etc/mongod.conf
    regexp: '^ *bindIp:'
    line: '  bindIp: 0.0.0.0'
    insertafter: '^net:'

- name: Restart MongoDB
  service:
    name: mongod
    state: restarted
